<?php

namespace Chekov\Bundle\EventBundle\Repository;

/**
 * EventDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventDateRepository extends \Doctrine\ORM\EntityRepository
{
}
