<?php

namespace Chekov\Bundle\EventBundle\Repository;

/**
 * EventTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
