<?php

namespace Chekov\Bundle\EventBundle\Repository;

/**
 * PlanItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanItemRepository extends \Doctrine\ORM\EntityRepository
{
}
